### ISSUE TITLE
Option for cpu to search for external modules

### ISSUE THREAD

**Issue by saper** [marekjm/viuavm#81]
I'd like to move `tests/compiled` under the `build/test` directory. We might even assemble tests in Makefile. (I'd like to be able to remove `build` completely from the git repo, support out-of-tree builds and have the source directory easily read-only).

For this to work nicely it would be good if tester runner could tell `cpu` where to look for `eximport`ed and `link`ed files. In `sample/asm/external/hello_world.asm` I have hardcoded the path, but we don't want this probably.

**Comment by marekjm** [comment]
I went with canonical solution to the problem and introduced an environment variable: `VIUAPATH`. It is a colon-separated lists of paths machine should search when looking for modules.

Paths on `VIUAPATH` are searched *before* machine looks into any hardcoded path. To append paths *after* hardcoded ones, use `VIUAAFTERPATH`.
